fossasia/labs.fossasia.org

posts/foresight-fedora-import.md
posts/mobile-search-app.md
posts/opencoin-digital-cash-app.md
posts/patternshare-design-and-measurement-tables.md
posts/pike-packaging.md
posts/sTeam-tooling.md
posts/sTeam-webinterface-with-REST.md
posts/sTeam-weblog.md
posts/sTeam-website-for-BLUG.md
posts/smalltalk-REST-api.md
posts/smalltalk-amber-tutorial.md
posts/smalltalk-file-editor.md
posts/smalltalk-postgresql-server.md
posts/smalltalk-search-app.md
posts/smalltalk-sql-parser.md
posts/sup-replace-rmail-with-mail.md
posts/valentina-port.md
posts/valentina-search-and-import.md

Fixed https://github.com/fossasia/labs.fossasia.org/issues/13

Use variables for idea fields

---

index.md

show pointer on open and close project buttons

---

_posts/2015-03-08-toolbox-fossasia-api.md

Fixed https://github.com/fossasia/labs.fossasia.org/issues/40

Fix Markdown Formatting

---

_layouts/index.html

Fix https://github.com/fossasia/labs.fossasia.org/issues/45

Add blog tab and fix home link

---

_layouts/index.html
_layouts/project.md

Scripts load faster when loaded after the dom and html5 doctype

Some Changes

---

_includes/post-detail.html
_posts/2015-03-18-fossasia-event-app.md
ideas.md
stylesheets/user.css

@mariobehling Maybe this was what you wanted ?

Add table of contents

---

_posts/2014-03-03-valentina-port.md
_posts/2015-03-04-ayab-port.md
_posts/2015-03-05-openwrt-bootstrap3-theme.md
_posts/2015-03-08-toolbox-fossasia-api.md
stylesheets/user.css

Reverts fossasia/labs.fossasia.org#57 does not solve the issue and CSS should stay compatible with other parts of FOSSASIA sites.

Revert "Fix links and remove project list indent"

---

javascripts/custom.js

Fix no-project script

---

_posts/2015-03-16-Timeline-Search-Navigation-loklaknet.md

- colums has been converted to columns

Fixes a typo error that was present on the idea page

---

_includes/post-detail.html
ideas.md
stylesheets/user.css

fix https://github.com/fossasia/labs.fossasia.org/issues/56

Improve Table of Contents layout

---

_posts/2014-03-03-valentina-port.md
_posts/2014-03-03-valentina-search-and-import.md
_posts/2015-01-10-sTeam-webinterface-with-REST.md
_posts/2015-01-10-sTeam-website-for-BLUG.md
_posts/2015-01-10-smalltalk-file-editor.md
_posts/2015-01-10-sup-replace-rmail-with-mail.md
_posts/2015-01-13-smalltalk-sql-parser.md
_posts/2015-01-15-sTeam-weblog.md
_posts/2015-01-15-smalltalk-amber-tutorial.md
_posts/2015-03-04-ayab-port.md
_posts/2015-03-05-openwrt-bootstrap3-theme.md
_posts/2015-03-05-steam-rest-api.md
_posts/2015-03-18-knitting-machine-library.md
ideas.md
stylesheets/user.css

Use <br> tags

---

_includes/post-detail.html
_layouts/project.md

Fix https://github.com/fossasia/labs.fossasia.org/issues/77 and https://github.com/fossasia/labs.fossasia.org/issues/59

Fix Headings and Remove HR

---

_includes/post-detail.html

Fix https://github.com/fossasia/labs.fossasia.org/issues/60

Fix space conflicts

---

_posts/2014-03-03-opencoin-digital-cash-app.md
_posts/2014-03-03-valentina-search-and-import.md
_posts/2015-01-10-sTeam-webinterface-with-REST.md
_posts/2015-01-10-sTeam-website-for-BLUG.md
_posts/2015-01-10-smalltalk-REST-api.md
_posts/2015-01-10-smalltalk-file-editor.md
_posts/2015-01-10-smalltalk-search-app.md
_posts/2015-01-15-smalltalk-amber-tutorial.md
_posts/2015-03-16-Timeline-Search-Navigation-loklaknet.md
_posts/2015-03-18-fossasia-event-management.md
_posts/2015-03-18-knitting-machine-GUI.md
_posts/2015-03-19-libre-mesh-bgp-interoperability.md
_posts/2015-03-19-online-community-communications.md
_posts/2015-03-24-blogger-wall.md
ideas.md
index.md

Fix https://github.com/fossasia/labs.fossasia.org/issues/43

Fix spelling and grammar errors

---

_posts/2015-03-24-expeyes.md
ideas.md
index.md

Please help in adding ExpEYES to ideas at labs.fossasia.org

ExpEYES Pocket Science Lab

---

ideas.md

This gives some criteria that FOSSASIA considers in evaluating proposals (based on email from mb@mariobehling.de). (Do I need to resubmit the pull request for the typo correction in 3824ce1?

Add factors to consider to ideas page.

---

gsoc.html

HTML page for GSOC project ideas created using github API.

GSOC Ideas Page

---

new/gsoc.html

The whole div can now be embedded into the the new website to mimic the old site's design style.

Draft for #89

---

new/ideas.html

Done as stated by @mariobehling on issue #89 
Please check it out sir.
Please accept it @sudheesh001 @mananwason @jig08 @nikunjness @roonyh @mariobehling .
Link to task: https://codein.withgoogle.com/dashboard/task-instances/6579903273107456/?sp-page=1
-Hope it does the trick...
-Enjoying last working days at GCI

Added issues section. Resolves issue #89

---

new/ideas.html

Done as stated by @mariobehling, @SaptakS  on issue #89 
Please check it out sir.
Please accept it @sudheesh001 @mananwason @jig08 @nikunjness @roonyh @mariobehling .
Link to task: https://codein.withgoogle.com/dashboard/task-instances/6579903273107456/?sp-page=1
-Hope it does the trick...
-Enjoying last working days at GCI

Added section issues, Part  II done to fix a bug. Resolves #89 as stated by Saptak and mariobehling

---

new/archive.html
new/ideas.html

Links in the content corrected. Archive.html modified to comply with the present design.

links corrected, archive.html modified

---

new/archive.html
new/ideas.html

Added the default link styles to read more and content table.

Added styling to the links

---

ideas.html

1. Refactors jquery code inserted in ideas.html page.
Further suggestions:
CSS and Jquery code is included inside html file. I propose to make separate files for style and script

Refactors jquery for gsoc-ideas page

---

ideas.html

https://github.com/fossasia/labs.fossasia.org/pull/107#event-526367675

Made the background white on suggestion of mariobehling

---

archive.html
ideas.html

Link for list in ideas.html and archive.html modifed

---

ideas.html

Fixes all three issues in #118 
I have removed the bullets in front of links.

Fixes issue #118

---

css/theme-lava.css

4th part of Issue #118 resolved.

fontSize decreased

---

index.html

@mariobehling updated to change the technologies mentioned for susper.

update to change susper technologies

---

ideas.html

I have fixed the issue #183 by making few minor changes in the line 403, 415, 419. Detailed description about the changes and problems with the previous code explained in the comments of the issue.

Fixed the issue #183 in which android data not showing up

---

index.html

1. "... provide a personal assistant for ~~to~~ users ..."
2. "... used ~~insidechat~~ applications ..."  ->  "...used inside chat applications ..."

Fix typos in SUSI.AI section of labs.fossasia.org

---

index.html

google, github, and flickr
#235 fixed

Added social links

---

index.html

Fixes #235 
***Added github icon at top menu bar and to the bottom***

Fixed "missing social links Issue #235"

---

index.html

Fixes issue #250 
Added link to map marker 
also added an hr at the bottom

Fixes#250. Update index.html

---

index.html

Fixes #254 
[Deploy Link](https://saarthakchats.github.io/aloobhonda/)

Fixes #254 :Added more social icons, fixed bugged icons

---

index.html

You can find the changes in the footer region :D 
#259 , i've fixed this issue !!

Added Hover-over text for better navigation !! (Issue no. #259 fixed :D)

---

index.html

correct position for links of github repo and sciencehack

---

.travis.yml
css/custom.css
index.html

Reverts fossasia/labs.fossasia.org#300

Revert "Aligned Links in Projects Sections"

---

css/custom.css
index.html

- [Preview Link](https://ksninja.github.io/labs.fossasia.org/)
- Fixes #315 
There was just a small bug in the GSoC section . Fixed it .
Improved the size and spacing between social media links in the footer .
- - - - - - - - - - - -

Make GSoc Section responsive and improve social links in footer

---

css/theme-lava.css
index.html

Add scroll bar to dropdowns and add a max-height. So it's never overlapped.
Organise some links in the nav bar to a drop-down. (Subscribe, Blog, Donate, ---> Other)
So it's never overlapped when resizing the width.
Fix sidebar overlapping.
https://github.com/fossasia/labs.fossasia.org/issues/313
Preview link - https://stedirisuriya.github.io/labs.fossasia.org/
Thank you!

[Fixed #313] Resolve issues on nav bar

---

index.html

- Corrects info, links, images for Neurolab Android and Hardware
- Visit https://kualeyi.github.io/labs.fossasia.org#neuroflight
- Fixes #323
The following two screenshots were captured approximately at the anchor `neuroflight`.
Before:
After:

Corrects Neurolab/flight in index.html

---

index.html

I was able to fix the issue which was on the FOSSASIA lab page.
Fixes: #331
Here is the Preview Link:- https://shreeshjha.github.io/labs.fossasia.org/

 Add and correct information in Index.html

---

index.html

[Preview Link](https://niteshkumarniranjan.github.io/labs.fossasia.org/)

Fixes Projects Layout Alternation (#333)

---

index.html

Implemented top menu bar in the same way as on fossasia.org and according to issue #335

Implement top menu bar in the same way as on fossasia.org #335

---

index.html

In respond to bug issues raised [here](https://github.com/fossasia/labs.fossasia.org/issues/346#issue-404947005) few of them has been resolved.
Please have a look.
PS: This is my first contribution to Open-Source

Updated FOSSASIA Logo link and Resolved Code-IN bug

---

css/custom.css
ideas.html
index.html

Added the back to top button (arrow) for easy navigation to the top as previously there was a link at the bottom which was not visible and the website needed a button like this for better user interface.
--FIXES #362 
Preview link 
https://imrrahul.github.io/labs.fossasia.org/

Added Back to Top button for easy navigation

---

css/custom.css
ideas.html
index.html

Reverts fossasia/labs.fossasia.org#363

Revert "Added Back to Top button for easy navigation"

---

index.html

Ideas.html link added in project menu of index.html,  solving the issue #347

Ideas link added in project menu

---

CNAME
ideas.html

Add space below lists on website - #357.

#357 - Add space below lists on website 

---

index.html

Navigate to correct area

---

index.html

Reverts fossasia/labs.fossasia.org#384

Revert "Navigate to correct area"

---

index.html

fixes: #376
Now the links  navigate to correct aeea

Fixes #376 . Navigates links to correct area

---

index.html

fixes : #386
the white space above the area does not get expanded

Fixes #386

---

index.html

Currently, this websites lacks a link to GitLab of FOSSASIA. I've added a link to FOSSASIA's GitLab account. Here's the deployment link:
https://wasif.codes/labs.fossasia.org/

Add GitLab link in footer

---

index.html
projects.html

The purpose is to update the new FOSSASIA address according to issue #407 
- Replace the new address in relevant pages.
- Replace the openstreet map link with the new links.
https://kumuditha-udayanga.github.io/labs.fossasia.org

Update new FOSSASIA Address

---

index.html

fixed issue #397 get rid of horizontal scrolling on mobile.

---

css/theme-lava.css

Fixes #391
Made width of "ideas" section same as other areas
Demo: https://darshancool25.github.io/labs.fossasia.org/
**Screenshot :**

Fixes #391 : Widened the "ideas" section

---

index.html

Fixes issue #417 of labs.fossasia.org
For the purpose of this merge request I have added yaydoc.org link above the meilix link in the drop down list on labs fossasia website.
Apart there were also some concerns regarding the last option not being displayed thus I have increased the drop down list size and hence now all the options are being displayed.
Preview Link : https://aryanguls.github.io/labs.fossasia.org/
@mariobehling @hpdang Mentors please review.

Updated Dropdown list on FOSSASIA Website By Adding Yaydoc 

---

index.html

Add Weibo, Vk, Wikipedia icon to the footer of the website.
The review link: https://hoangdatngo.github.io/labs.fossasia.org/

Add more icon to the footer of the website
